#164 Export outputs with dynamic models
dynawo/dynaflow-launcher pull request #183
Opened 2021-07-08 09:04 UTC by lecourtoisflo

2021-07-09 07:46 UTC, rosiereflo requested changes

2021-07-19 06:02 UTC, lecourtoisflo commented on sources/Outputs/include/Dyd.h
> +    const algo::DynModelDefinitions& models;                                     ///< the list of models to export
OK

2021-07-19 06:04 UTC, lecourtoisflo commented on sources/Outputs/include/Dyd.h
> +  writeDynModelMacroConnectors(const std::unordered_set<std::string>& usedMacros,
OK

2021-07-19 06:11 UTC, lecourtoisflo commented on sources/Outputs/include/Dyd.h
> +   * @param macros total list of macro connections defined for models
OK

2021-07-19 06:12 UTC, lecourtoisflo commented on sources/Outputs/include/Dyd.h
> +  static std::vector<boost::shared_ptr<dynamicdata::MacroConnector>>
This vector is built inside the function. It will not be a copy but a move

2021-07-19 06:12 UTC, lecourtoisflo commented on sources/Outputs/include/Dyd.h
> +   * @brief Write macro connec for dynamic model
OK

2021-07-19 06:13 UTC, lecourtoisflo commented on sources/Outputs/include/Dyd.h
> +   * @brief Write model for dynamic model
OK

2021-07-19 06:15 UTC, lecourtoisflo commented on sources/Outputs/include/Dyd.h
>        correspondence_lib_;  ///< Correspondence between generator model type and library name in dyd file
OK

2021-07-19 06:16 UTC, lecourtoisflo commented on sources/Outputs/include/Par.h
> +     * @param models list of models definitions
OK

2021-07-19 06:16 UTC, lecourtoisflo commented on sources/Outputs/include/Dyd.h
> +     * @param models the list of models to use
OK

2021-07-19 06:16 UTC, lecourtoisflo commented on sources/Outputs/include/Par.h
> +     * @param counters the counters definitions to use
I lert counters for the parameter and update the name of the attribute

2021-07-19 06:17 UTC, lecourtoisflo commented on sources/Outputs/include/Par.h
> +    const algo::ShuntCounterDefinitions& counters;                                ///< Counters to use
OK

2021-07-19 06:19 UTC, lecourtoisflo commented on sources/Outputs/include/Par.h
> +    const algo::DynModelDefinitions& models;                                      ///< list of defined models
OK

2021-07-19 06:19 UTC, lecourtoisflo commented on sources/Outputs/include/Par.h
> +   * @brief Write set for models
OK

2021-07-19 06:20 UTC, lecourtoisflo commented on sources/Outputs/include/Par.h
> +   * @brief Retrieves the first component connected through the dynamic model to a transfo
OK

2021-07-19 06:21 UTC, lecourtoisflo commented on sources/Outputs/include/Par.h
> +   * @returns the tfo id the dynamic model is connected to, nullopt if not found
OK

2021-07-19 06:22 UTC, lecourtoisflo commented on sources/Outputs/src/Dyd.cpp
> +  for (const auto& model : def_.models.models) {
If we rename the attributes models and models.model, it is enought for me. The point of an iterator is to be as simple as an index

2021-07-19 06:22 UTC, lecourtoisflo commented on etc/DFLMessages_en_GB.dic
> +DynModelMacroNotDefined       =     Macro %1% used in model not defined
OK

2021-07-19 06:23 UTC, lecourtoisflo commented on sources/Outputs/src/Dyd.cpp
> +  // Here we compute the number of connections performed by macro connection, in order to generate the coresponding
OK

2021-07-19 06:24 UTC, lecourtoisflo commented on sources/Outputs/src/Dyd.cpp
> +  std::map<std::string, std::tuple<unsigned int, unsigned int>> indexes;
OK

2021-07-19 06:24 UTC, lecourtoisflo commented on sources/Outputs/src/Par.cpp
> +const std::string Par::componentIdTag_("@TFO@");
updated to componentIdTag_

2021-07-19 06:25 UTC, lecourtoisflo commented on sources/Outputs/include/Par.h
> +  static boost::shared_ptr<parameters::ParametersSet> writeDynModelSet(const inputs::SettingXmlDocument::Set& set,
OK

2021-07-19 06:27 UTC, lecourtoisflo commented on sources/Outputs/src/Par.cpp
> +      // case voltage level not in network, skip
Then we will write 0 in the par file

2021-07-19 06:28 UTC, lecourtoisflo commented on sources/Outputs/src/Par.cpp
> +    // TODO(lecourtoisflo) extensions ?
Will be processed in another PR (already ready to be reviewed) when active season extension is integrated into dynawo

2021-07-19 06:36 UTC, lecourtoisflo commented on tests/outputs/TestDyd.cpp
> +  auto node = dfl::inputs::Node::build("Slack", vl, 100., {});
90% pour ces 2 fichiers

2021-07-20 09:26 UTC, rosiereflo commented on sources/Outputs/src/Par.cpp
> +const std::string Par::componentIdTag_("@TFO@");
Transfo->Transformer

2021-07-20 09:29 UTC, rosiereflo commented on tests/outputs/TestDyd.cpp
> +  auto node = dfl::inputs::Node::build("Slack", vl, 100., {});
Can you check that new code is covered and add unit tests if not?

2021-07-20 09:31 UTC, rosiereflo commented on sources/Outputs/src/Par.cpp
> +      // case voltage level not in network, skip
where is this done?

2021-07-20 11:21 UTC, lecourtoisflo commented on tests/outputs/TestDyd.cpp
> +  auto node = dfl::inputs::Node::build("Slack", vl, 100., {});
it is

2021-07-22 13:24 UTC, lecourtoisflo commented on sources/Outputs/src/Par.cpp
> +const std::string Par::componentIdTag_("@TFO@");
OK

2021-07-23 06:49 UTC, rosiereflo approved these changes

2021-07-23 06:49 UTC, merged