#280 remove results folder before running tests again
dynawo/dynaflow-launcher pull request #293
Opened 2022-01-21 14:27 UTC by marcochiaramello

Closes #280

2022-01-21 14:29 UTC, gautierbureau requested changes

2022-01-21 14:29 UTC, gautierbureau commented on scripts/envDFL.sh
> +    pushd $DYNAFLOW_LAUNCHER_HOME > /dev/null
you need a popd after the find then

2022-01-21 14:30 UTC, marcochiaramello commented on scripts/envDFL.sh
> +    pushd $DYNAFLOW_LAUNCHER_HOME > /dev/null
done , thx

2022-01-21 14:34 UTC, gautierbureau approved these changes

2022-01-21 14:37 UTC, gautierbureau commented
Thinking about it I think we should maybe have a name less generic than "results" because if somebody has a folder with this name in its folder it will delete it... Maybe resultsTestsTmp to make sure nobody would use the name ?

2022-01-21 17:11 UTC, marcochiaramello commented
> Thinking about it I think we should maybe have a name less generic than "results" because if somebody has a folder with this name in its folder it will delete it... Maybe resultsTestsTmp to make sure nobody would use the name ?

I quite agree with the proposal, I'll more results into resultsTestsTmp folder everywhere and adapt the fix

2022-01-24 08:52 UTC, gautierbureau approved these changes

2022-01-24 09:59 UTC, merged