#304 use dictionary and log system from dynawo core
dynawo/dynaflow-launcher pull request #305
Opened 2022-02-09 10:44 UTC by rosiereflo

closes #304

2022-02-09 10:54 UTC, rosiereflo commented
Let me fix the coverage

2022-02-09 11:39 UTC, marcochiaramello requested changes

2022-02-09 11:39 UTC, marcochiaramello commented on etc/Dictionaries/DFLLog_en_GB.dic
> +// Copyright (c) 2020, RTE (http://www.rte-france.com)
2022

2022-02-09 11:39 UTC, marcochiaramello commented on sources/Common/include/Log.h
> + *  to the message (+ optional arguments if the message need)
remove "to" before "the message"

2022-02-10 08:29 UTC, rosiereflo commented on etc/Dictionaries/DFLLog_en_GB.dic
> +// Copyright (c) 2020, RTE (http://www.rte-france.com)
Done

2022-02-10 08:29 UTC, rosiereflo commented on sources/Common/include/Log.h
> + *  to the message (+ optional arguments if the message need)
Done

2022-02-10 08:56 UTC, marcochiaramello approved these changes

2022-02-10 08:56 UTC, merged