#249 mpi
dynawo/dynaflow-launcher pull request #318
Opened 2022-02-15 09:31 UTC by rosiereflo

closes #249 
follows https://github.com/dynawo/dynawo-algorithms/pull/116

2022-03-17 09:07 UTC, marcochiaramello requested changes

2022-03-17 09:07 UTC, marcochiaramello commented on scripts/dynaflow-launcher.sh
> +    shift # past value
shift 2 ?

2022-03-17 09:07 UTC, marcochiaramello commented on scripts/envDFL.sh
> +        shift # past value
shift 2 ?

2022-03-22 14:57 UTC, gautierbureau reviewed
for me it is ok

2022-03-23 12:17 UTC, rosiereflo commented on scripts/dynaflow-launcher.sh
> +    shift # past value
solved

2022-03-23 12:17 UTC, rosiereflo commented on scripts/envDFL.sh
> +        shift # past value
solved

2022-03-23 12:17 UTC, rosiereflo commented on README.md
> +[![Quality Gate Status](https://sonarcloud.io/api/project_bEAD
Nope! solved.

2022-03-23 12:17 UTC, rosiereflo commented on scripts/dynaflow-launcher.sh
> +export DYNAWO_DDB_DIR=$DYNAFLOW_LAUNCHER_EXTERNAL_DDB $DYNAWO_HOME/ddb
You are right, only 1 path is supported. solved.

2022-03-23 12:17 UTC, rosiereflo commented on scripts/envDFL.sh
> +    if [ ! -f $3 ]; then
I think I got most of them.

2022-03-23 12:36 UTC, gautierbureau approved these changes

2022-03-24 09:44 UTC, marcochiaramello approved these changes

2022-03-25 12:48 UTC, gautierbureau commented
```
RETURN_CODE=$?
return $RETURN_CODE
```

are missing in cmake_configure and cmake_build

2022-03-25 12:57 UTC, gautierbureau requested changes

2022-03-25 12:57 UTC, gautierbureau commented on 3rdParty/CMakeLists.txt
> +set(MPI_HOME ${CMAKE_INSTALL_PREFIX}/mpich)
remove to be able to find system mpich

2022-03-25 12:57 UTC, gautierbureau commented on 3rdParty/CMakeLists.txt
> +  set(MPI_HOME ${CMAKE_INSTALL_PREFIX}/mpich)
remove to be able to find system mpich

2022-03-25 13:02 UTC, rosiereflo commented on 3rdParty/CMakeLists.txt
> +set(MPI_HOME ${CMAKE_INSTALL_PREFIX}/mpich)
solved

2022-03-25 13:02 UTC, rosiereflo commented on 3rdParty/CMakeLists.txt
> +  set(MPI_HOME ${CMAKE_INSTALL_PREFIX}/mpich)
solved

2022-03-25 13:17 UTC, gautierbureau approved these changes

2022-03-29 14:32 UTC, merged