#464 Add connection model-model and shunt single association
dynawo/dynaflow-launcher pull request #466
Opened 2022-10-18 08:53 UTC by AdrienBlassiau

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [x] unit tests and non regression tests were added (update of inputs, outputs, SA, algos)
- [x] main documentation was updated (update of input/output file)
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

Related to https://github.com/dynawo/dynaflow-launcher/issues/464

2023-02-21 10:37 UTC, cossartque commented on documentation/configuringDynaflowLauncher/DynaflowLaunchersInputFiles.tex
> +\small{AssemblingPath} & \small{string} & \small{Path to the assembling file} & \small{nothing} \\
Already implemented

2023-02-21 10:37 UTC, cossartque commented on documentation/functionalDoc/functionalDoc.tex
> +\section{Assembling and Setting files}
Check if not already implemented

2023-02-21 10:38 UTC, cossartque commented
Could you also resolve the conflicts ? Thanks

2023-04-28 07:21 UTC, rosiereflo requested changes

2023-05-02 14:18 UTC, jlbouchot commented on etc/xsd/assembling.xsd
> +    <xs:attribute name="name" type="xs:string"/>
I believe this is okay -- unless my understanding is far fro, the truth. In a multipleAssociation case, one would want to connect *all* shunts connected to a given voltage level whereas in the singleAssociation case, one would want to target a specific shunt, independently of the other shunts connected to the same voltage level. 

This raises the (potential) question though of "What to do if a multipleAssociation is mentioned for a given voltage level and one of the shunts has a specific single association too?" I'm guessing it doesn't matter much, but I could be wrong.

2023-05-17 06:57 UTC, rosiereflo approved these changes

2023-05-17 07:36 UTC, merged