#526 upadte dyd and par creation following OS 2673
dynawo/dynaflow-launcher pull request #537
Opened 2023-01-09 15:05 UTC by marcochiaramello

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [x] unit tests and non regression tests were added (update of inputs, outputs, SA, algos)
- [ ] main documentation was updated (update of input/output file)
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

2023-01-10 09:32 UTC, cossartque approved these changes

2023-01-10 10:26 UTC, rosiereflo requested changes

2023-01-10 10:26 UTC, rosiereflo commented on sources/Outputs/src/DydGenerator.cpp
> +  std::unordered_map<std::string, int> ModelNQIdGenNumber;
unsigned and coding style: modelNQIdGenNumber

2023-01-10 10:26 UTC, rosiereflo commented on sources/Outputs/src/DydGenerator.cpp
> +      ModelNQIdGenNumber[ModelNQId]++;
++ModelNQIdGenNumber[ModelNQId]; to avoid a useless copy

2023-01-11 13:01 UTC, rosiereflo approved these changes

2023-01-12 07:37 UTC, merged