476 nsa allow having a different configuration file for n and sa
dynawo/dynaflow-launcher pull request #551
Opened 2023-01-17 12:17 UTC by barondim

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [x] unit tests and non regression tests were added (update of inputs, outputs, SA, algos)
- [ ] main documentation was updated (update of input/output file)
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

2023-01-17 12:18 UTC, barondim commented
- [ ] Documentation to be updated

2023-01-17 12:19 UTC, barondim commented
Should I implement a NRT ?

2023-01-23 08:39 UTC, rosiereflo requested changes

2023-01-23 08:39 UTC, rosiereflo commented on etc/Dictionaries/DFLError_en_GB.dic
> +NoFlatStartingPointModeInSA   =     can't set starting point mode on flat when simulation is in SA
I would propose "flat mode cannot be used in security analysis"

2023-01-23 08:39 UTC, rosiereflo commented on sources/Inputs/include/Configuration.h
> +  void updateStartingPointMode(const boost::property_tree::ptree& tree, const bool sa_mode);
coding style: saMode

2023-01-23 08:39 UTC, rosiereflo commented on sources/Inputs/src/Configuration.cpp
> +    json_key = "sa." + key;
why not adding this directly in the key when calling update value?

2023-01-23 08:39 UTC, rosiereflo commented on sources/Inputs/src/Configuration.cpp
> +    helper::updateValue(useInfiniteReactiveLimits_, config, "InfiniteReactiveLimits", sa_mode);
if only a N value is given then it should override the default for SA

2023-02-06 14:14 UTC, barondim commented on sources/Inputs/include/Configuration.h
> +   * @param request is the simulation in N or SA ?
Test

2023-02-06 14:28 UTC, barondim commented on documentation/configuringDynaflowLauncher/DynaflowLaunchersInputFiles.tex
> +
Test

2023-02-13 10:48 UTC, rosiereflo approved these changes

2023-02-13 10:52 UTC, marcochiaramello approved these changes

2023-02-13 15:09 UTC, rosiereflo commented
Could you please squash the commits?

2023-02-16 13:00 UTC, merged