#514 Increase simulation time and event time when SVC are used
dynawo/dynaflow-launcher pull request #623
Opened 2023-04-03 13:23 UTC by rosiereflo

closes #514

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (update of inputs, outputs, SA, algos)
- [ ] main documentation was updated (update of input/output file)
- [ ] the corresponding milestone was added in the ticket and in this PR

2023-04-03 14:39 UTC, cossartque approved these changes

2023-04-03 14:39 UTC, cossartque commented
> ![image](https://user-images.githubusercontent.com/47146813/229534251-59e782f3-dc8e-4a59-8194-d03bd4ba0f6c.png)
> 
> For now I have put a duration of 2000s and an event at 500s what do you think? (Only if nothing was specified in the input configuration file)

The duration of 2000s is for N and N-1 ?

2023-04-04 05:49 UTC, rosiereflo commented
> 
> The duration of 2000s is for N and N-1 ?

Yes this is the current (safe) choice to make sure the SVC is stabilized. This is just a first attempt, we can refine it later on

2023-04-06 08:21 UTC, marcochiaramello requested changes

2023-04-06 08:21 UTC, marcochiaramello commented on sources/Context.h
> +                                                                              * @brief Context definition
comment is shift

2023-04-06 08:29 UTC, rosiereflo commented on sources/Context.h
> +                                                                              * @brief Context definition
done

2023-04-06 08:37 UTC, marcochiaramello approved these changes

2023-04-06 08:40 UTC, merged