#462 dumpstate nsa
dynawo/dynaflow-launcher pull request #635
Opened 2023-04-11 14:36 UTC by rosiereflo

SA
closes #462

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (update of inputs, outputs, SA, algos)
- [ ] main documentation was updated (update of input/output file)
- [ ] the corresponding milestone was added in the ticket and in this PR

2023-04-14 08:17 UTC, marcochiaramello requested changes

2023-04-14 08:17 UTC, marcochiaramello commented on tests/main_n_sa/reference/launch/branch_contingency/outputIIDM.xml
> +                <iidm:bus v="128.93988499712606" angle="11.814100908202946" nodes="0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22"/>
quite large differences on final values, why?
thx!

2023-04-18 10:01 UTC, rosiereflo commented on documentation/configuringDynaflowLauncher/DynaflowLaunchersInputFiles.tex
> +\textbf{The only parameter not elligible for this override is 'outputDir'.}
solved

2023-04-20 08:59 UTC, marcochiaramello approved these changes

2023-04-21 08:11 UTC, merged