#784 Nightly release and release without mpi (nightly-release.yml only)
dynawo/dynaflow-launcher pull request #801
Opened 2024-10-31 18:34 UTC by barondim

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (update of inputs, outputs, SA, algos)
- [ ] main documentation was updated (update of input/output file)
- [x] the corresponding milestone was added in the ticket and in this PR

2024-11-06 09:25 UTC, gautierbureau commented
we don't need to do it for Linux release

2024-11-06 09:46 UTC, barondim commented
> we don't need to do it for Linux release

On the dyn-algo task https://github.com/dynawo/dynawo-algorithms/pull/406 we build dyn-algo with and without MPI. Isn't it coherent to do the same with dfl ?

2024-12-02 09:59 UTC, gautierbureau approved these changes

2024-12-02 10:00 UTC, gautierbureau requested changes

2024-12-02 10:00 UTC, gautierbureau commented on sources/main.cpp
> +#ifdef _MPI_
should be encapsulated in the context I think

2024-12-02 10:34 UTC, barondim commented
- [ ] to be merged with https://github.com/dynawo/dynawo-algorithms/pull/441

2024-12-02 14:15 UTC, barondim commented
- [ ] to be merged with https://github.com/dynawo/dynawo-algorithms/pull/442

2024-12-04 08:43 UTC, gautierbureau approved these changes

2024-12-04 08:44 UTC, merged