#810 Add the possibility to zip the inputs and outputs for N simulation
dynawo/dynaflow-launcher pull request #820
Opened 2024-12-20 18:58 UTC by barondim

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (update of inputs, outputs, SA, algos)
- [ ] main documentation was updated (update of input/output file)
- [x] the corresponding milestone was added in the ticket and in this PR

2025-01-07 09:18 UTC, rosiereflo requested changes
It seems that the N output will not be zipped. Also, the documentation and tests needs to be updated.

2025-01-07 09:18 UTC, rosiereflo commented on scripts/envDFL.sh
> +    if [ -n "$ZIP_ARCHIVE" ]; then
Maybe we should add a check that the zip archive exists

2025-01-09 10:48 UTC, barondim commented on scripts/envDFL.sh
> +    if [ -n "$ZIP_ARCHIVE" ]; then
The check is made in the C++ code

2025-01-09 10:57 UTC, rosiereflo commented on scripts/envDFL.sh
> +    if [ -n "$ZIP_ARCHIVE" ]; then
yes, but it is also the case for network, config and contingencies files and yet they are tested in the other branch. This is to be homogeneous

2025-01-09 13:34 UTC, rosiereflo commented on sources/Common/src/ZipErrorMessage.cpp
> +  std::stringstream zipErrorStream;
Why overriding the messages sent by libzip? The general exception catch should be enough ?

2025-01-17 08:43 UTC, rosiereflo commented on sources/Context.cpp
> +    const boost::filesystem::path timelineFilePath = simu->getTimelineOutputFile();
No need to add new API in the core as we have the jobs somewhere

2025-01-17 10:43 UTC, barondim commented on sources/Context.cpp
> +    const boost::filesystem::path timelineFilePath = simu->getTimelineOutputFile();
I'm not sure it's possible to get the constraints, lost equipments and finalStatte output file names from the jobEntry_ attribute

2025-01-17 12:53 UTC, barondim commented
- [ ] to be merged with https://github.com/dynawo/dynawo/pull/3537

2025-01-21 10:24 UTC, barondim commented on sources/Common/src/ZipErrorMessage.cpp
> +  std::stringstream zipErrorStream;
The error message given by libzip is not always clear. When the zip::Error::LIBARCHIVE_INTERNAL_ERROR error code is thrown, the message is clear : ''Unrecognized archive format". But when the zip::Error::FILE_NOT_FOUND error code is thrown, only the name of the missing file is given. So the error message is not clear in that case.

2025-01-22 11:57 UTC, barondim commented on sources/main.cpp
> +        archive = zip::ZipInputStream::read(archivePath);
Why is it needed to read the archive ?

2025-01-22 12:12 UTC, barondim commented on sources/Common/src/Options.cpp
> -Options::areRequiredFilesMissing(const po::variables_map& vm, const boost::shared_ptr<zip::ZipFile>& archive) const {
So we totally abandon this check ?

2025-01-22 12:44 UTC, rosiereflo commented on sources/main.cpp
> +        archive = zip::ZipInputStream::read(archivePath);
it is used when it was already created by dynawo-algorithms and we complete it

2025-01-22 12:44 UTC, rosiereflo commented on sources/Common/src/Options.cpp
> -Options::areRequiredFilesMissing(const po::variables_map& vm, const boost::shared_ptr<zip::ZipFile>& archive) const {
it is done later in the code when trying to load the files

2025-01-22 15:28 UTC, merged